---
# tasks file for Ansible-BuildPython
- name: Install Updates
  apt:
    upgrade: dist
    update_cache: yes

- name: Install Python Build Dependencies
  apt:
    pkg: "{{ item.pkg }}"
    state: "{{ item.state }}"
    install_recommends: "{{ item.install_recommends }}"
  with_items:
    - "{{ PYTHON_BUILD_DEP }}"
    - "{{ PYTHON_ADDITIONAL_BUILD_DEP }}"

- name: Download and Extract Python {{ PYTHON_VERSION }} Tarball
  unarchive:
    src: "{{ PYTHON_TARBALL_URL }}"
    dest: "{{ PYTHON_SRC_LOCAL_PATH }}"
    remote_src: yes

- name: Run Python {{ PYTHON_VERSION }} Configure Script
  shell: "./configure {% for OPTION in PYTHON_CONFIGURE_OPTIONS %}{{ OPTION }}{% if not loop.last %} {% endif %}{% endfor %}"
  args:
    executable: "/bin/bash"
    chdir: "{{ PYTHON_SRC_LOCAL_PATH }}/Python-{{ PYTHON_VERSION }}"
  environment:
    CC: "{{ PYTHON_BUILD_ENV.CC }}"
    CFLAGS: "{{ PYTHON_BUILD_ENV.CFLAGS }}"
    LDFLAGS: "{{ PYTHON_BUILD_ENV.LDFLAGS }}"
    CPPFLAGS: "{{ PYTHON_BUILD_ENV.CPPFLAGS }}"

- name: Build and Install Python {{ PYTHON_VERSION }}
  shell: "{{ item }}"
  args:
    executable: "/bin/bash"
    chdir: "{{ PYTHON_SRC_LOCAL_PATH }}/Python-{{ PYTHON_VERSION }}"
  with_items:
    - "make -j{{ ansible_processor_vcpus }}"
    - "make install"

- name: Add Run-Time Linker Configuration for Python {{ PYTHON_VERSION }}
  template:
    src: "templates/etc/ld.so.conf.d/python-build.conf.j2"
    dest: "/etc/ld.so.conf.d/python-build.conf"

- name: Run ldconfig
  shell: "ldconfig"
  args:
    executable: "/bin/bash"

- name: Download get-pip.py Script
  get_url:
    url: "{{ PYTHON_PIP_SCRIPT_URL }}"
    dest: "/tmp/get-pip.py"
    mode: '0600'
  when: PYTHON_INSTALL_PIP

- name: Run get-pip.py Script
  shell: "{{ PYTHON_INSTALL_BIN }} /tmp/get-pip.py"
  args:
    executable: "/bin/bash"
  when: PYTHON_INSTALL_PIP

- name: Remove get-pip.py Script
  file:
    path: "/tmp/get-pip.py"
    state: absent
  when: PYTHON_INSTALL_PIP

- name: Install virtualenv
  pip:
    name: "virtualenv"
    state: "present"
    executable: "{{ PYTHON_INSTALL_BIN }}"
  vars:
    ansible_python_interpreter: "{{ PYTHON_INSTALL_BIN }}"
  when: PYTHON_INSTALL_VIRTUALENV
